language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
  allow_failures:
    - php: 5.5


before_script:
  - /home/travis/.phpenv/versions/5.3.27/bin/composer.phar self-update
  - composer install --dev --no-interaction
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION


env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

script:
  - mkdir -p build/logs
  - phpunit