<?php
return array(
    'input' => array(
        'ID' => 5,
        'post_title' => 'New Version',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 0,
        'intro' => array(
            'ID' => 6,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'intro_result' => array(
            'ID' => 7,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'outro' => array(
            'ID' => 8,
            'post_content' => 'Outro contents [kwps_result result=result-profile]',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'result_profiles' => array(
            1 => array(
                //'ID' => 9,
                //'post_parent' => 5,
                '_kwps_sort_order' => 0,
                '_kwps_min_value' => 0,
                '_kwps_max_value' => 25,
                'post_title' => 'Result profile 1',
                'post_status' => 'draft',
            ),
            2 => array(
                //'ID' => 10,
                //'post_parent' => 5,
                '_kwps_sort_order' => 1,
                '_kwps_min_value' => 26,
                '_kwps_max_value' => 50,
                'post_title' => 'Result profile 2',
                'post_status' => 'draft',
            ),
            3 => array(
                //'ID' => 11,
                //'post_parent' => 5,
                '_kwps_sort_order' => 2,
                '_kwps_min_value' => 51,
                '_kwps_max_value' => 100,
                'post_title' => 'Result profile 3',
                'post_status' => 'draft',
            ),
        ),
        'question_groups' => array(
            0 => array(
                'ID' => 9,
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'post_parent' => 5,
                'questions' => array(
                    1 => array(
                        'ID' => 10,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'post_parent' => 9,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 11,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                                '_kwps_answer_option_value' => 5,
                            ),
                            1 => array(
                                'ID' => 12,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                                '_kwps_answer_option_value' => 10,
                            ),
                            2 => array(
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                        ),
                    ),
                ),
            ),

        ),
    ),
    'expected_output' => array(
        'errors' => true,
        'test_modus_errors' => array(),
        'data' => array(
            'ID' => 5,
            'post_title' => 'New Version',
            'post_parent' => 4,
            'post_status' => 'draft',
            '_kwps_sort_order' => 0,
            'errors' => array(),
            'intro' => array(
                'ID' => 6,
                'post_content' => 'Intro contents',
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_parent' => 5,
                'errors' => array(),
            ),
            'intro_result' => array(
                'ID' => 7,
                'post_content' => 'Intro result contents',
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_parent' => 5,
                'errors' => array(),
            ),
            'outro' => array(
                'ID' => 8,
                'post_content' => 'Outro contents [kwps_result result=result-profile]',
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_parent' => 5,
                'errors' => array(),
            ),
            'result_profiles' => array(
                1 => array(
                    //'ID' => 9,
                    //'post_parent' => 5,
                    '_kwps_sort_order' => 0,
                    '_kwps_min_value' => 0,
                    '_kwps_max_value' => 25,
                    'post_title' => 'Result profile 1',
                    'post_status' => 'draft',
                    'errors' => array(),
                ),
                2 => array(
                    //'ID' => 10,
                    //'post_parent' => 5,
                    '_kwps_sort_order' => 1,
                    '_kwps_min_value' => 26,
                    '_kwps_max_value' => 50,
                    'post_title' => 'Result profile 2',
                    'post_status' => 'draft',
                    'errors' => array(),
                ),
                3 => array(
                    //'ID' => 11,
                    //'post_parent' => 5,
                    '_kwps_sort_order' => 2,
                    '_kwps_min_value' => 51,
                    '_kwps_max_value' => 100,
                    'post_title' => 'Result profile 3',
                    'post_status' => 'draft',
                    'errors' => array(),
                ),
            ),
            'question_groups' => array(
                0 => array(
                    'ID' => 9,
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_title' => 'Question page 1',
                    'post_content' => 'These are the questions of page 1',
                    'post_parent' => 5,
                    'errors' => array(),
                    'questions' => array(
                        1 => array(
                            'ID' => 10,
                            '_kwps_sort_order' => 0,
                            'post_status' => 'draft',
                            'post_content' => 'Question 1',
                            'post_parent' => 9,
                            'errors' => array(),
                            'answer_options' => array(
                                0 => array(
                                    'ID' => 11,
                                    '_kwps_sort_order' => 0,
                                    'post_content' => 'Answer option 1',
                                    'post_status' => 'draft',
                                    'post_parent' => 10,
                                    '_kwps_answer_option_value' => 5,
                                    'errors' => array(),
                                ),
                                1 => array(
                                    'ID' => 12,
                                    '_kwps_sort_order' => 1,
                                    'post_content' => 'Answer option 2',
                                    'post_status' => 'draft',
                                    'post_parent' => 10,
                                    '_kwps_answer_option_value' => 10,
                                    'errors' => array(),
                                ),
                                2 => array(
                                    '_kwps_sort_order' => 2,
                                    'post_content' => 'Answer option 3',
                                    'post_status' => 'draft',
                                    'post_parent' => 10,
                                    'errors' => array(
                                        '_kwps_answer_option_value' => 'Required',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);