<?php
return array(
    'input' => array(
        'ID' => 5,
        'post_title' => 'New Version',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 1,
        'intro' => array(
            'ID' => 6,
            'post_parent' => 5,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 1,
            'post_status' => 'draft',
        ),
        'intro_result' => array(
            'ID' => 7,
            'post_parent' => 5,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 1,
            'post_status' => 'draft',
        ),
        'outro' => array(
            'ID' => 8,
            'post_parent' => 5,
            'post_content' => 'Outro contents [kwps_result result=result-profile]',
            '_kwps_sort_order' => 1,
            'post_status' => 'draft',
        ),
        'question_groups' => array(
            1 => array(
                'ID' => 9,
                'post_parent' => 5,
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'questions' => array(
                    1 => array(
                        'ID' => 10,
                        'post_parent' => 9,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            1 => array(
                                'ID' => 11,
                                'post_parent' => 10,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 5,
                            ),
                            2 => array(
                                'ID' => 12,
                                'post_parent' => 10,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 10,
                            ),
                            3 => array(
                                'ID' => 13,
                                'post_parent' => 10,
                                '_kwps_sort_order' => 3,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 15,
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 14,
                        'post_parent' => 9,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            1 => array(
                                'ID' => 15,
                                'post_parent' => 14,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 5,
                            ),
                            2 => array(
                                'ID' => 16,
                                'post_parent' => 14,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'trash',
                                '_kwps_answer_option_value' => 10,
                            ),
                            3 => array(
                                'ID' => 17,
                                'post_parent' => 14,
                                '_kwps_sort_order' => 3,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 15,
                            ),
                        ),
                    ),
                ),
            ),
            2 => array(
                'ID' => 18,
                'post_parent' => 5,
                '_kwps_sort_order' => 2,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 2',
                'questions' => array(
                    1 => array(
                        'ID' => 19,
                        'post_parent' => 18,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            1 => array(
                                'ID' => 20,
                                'post_parent' => 19,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'trash',
                                '_kwps_answer_option_value' => 5,
                            ),
                            2 => array(
                                'ID' => 21,
                                'post_parent' => 19,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 10,
                            ),
                            3 => array(
                                'ID' => 22,
                                'post_parent' => 19,
                                '_kwps_sort_order' => 3,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 15,
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 23,
                        'post_parent' => 18,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            1 => array(
                                'ID' => 24,
                                'post_parent' => 23,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 5,
                            ),
                            2 => array(
                                'ID' => 25,
                                'post_parent' => 23,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 10,
                            ),
                            3 => array(
                                'ID' => 26,
                                'post_parent' => 23,
                                '_kwps_sort_order' => 3,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                '_kwps_answer_option_value' => 15,
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'expected_output' => array(
        'errors' => false,
        'test_modus_errors' => array(),
        'data' => array(
            'ID' => 5,
            'post_title' => 'New Version',
            'post_parent' => 4,
            'post_status' => 'draft',
            '_kwps_sort_order' => 1,
            '_kwps_view_count' => 0,
            'intro' => array(
                'ID' => 6,
                'post_parent' => 5,
                'post_content' => 'Intro contents',
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
            ),
            'intro_result' => array(
                'ID' => 7,
                'post_parent' => 5,
                'post_content' => 'Intro result contents',
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
            ),
            'outro' => array(
                'ID' => 8,
                'post_parent' => 5,
                'post_content' => 'Outro contents [kwps_result result=result-profile]',
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
            ),
            'question_groups' => array(
                0 => array(
                    'ID' => 9,
                    'post_parent' => 5,
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_title' => 'Question page 1',
                    'post_content' => 'These are the questions of page 1',
                    'questions' => array(
                        0 => array(
                            'ID' => 10,
                            'post_parent' => 9,
                            '_kwps_sort_order' => 0,
                            'post_status' => 'draft',
                            'post_content' => 'Question 1',
                            'answer_options' => array(
                                0 => array(
                                    'ID' => 11,
                                    'post_parent' => 10,
                                    '_kwps_sort_order' => 0,
                                    'post_content' => 'Answer option 1',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 5,
                                ),
                                1 => array(
                                    'ID' => 12,
                                    'post_parent' => 10,
                                    '_kwps_sort_order' => 1,
                                    'post_content' => 'Answer option 2',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 10,
                                ),
                                2 => array(
                                    'ID' => 13,
                                    'post_parent' => 10,
                                    '_kwps_sort_order' => 2,
                                    'post_content' => 'Answer option 3',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 15,
                                ),
                            ),
                        ),
                        1 => array(
                            'ID' => 14,
                            'post_parent' => 9,
                            '_kwps_sort_order' => 1,
                            'post_status' => 'draft',
                            'post_content' => 'Question 2',
                            'answer_options' => array(
                                0 => array(
                                    'ID' => 15,
                                    'post_parent' => 14,
                                    '_kwps_sort_order' => 0,
                                    'post_content' => 'Answer option 1',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 5,
                                ),
                                1 => array(
                                    'ID' => 17,
                                    'post_parent' => 14,
                                    '_kwps_sort_order' => 1,
                                    'post_content' => 'Answer option 3',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 15,
                                ),
                            ),
                        ),
                    ),
                ),
                1 => array(
                    'ID' => 18,
                    'post_parent' => 5,
                    '_kwps_sort_order' => 1,
                    'post_status' => 'draft',
                    'post_title' => 'Question page 1',
                    'post_content' => 'These are the questions of page 2',
                    'questions' => array(
                        0 => array(
                            'ID' => 19,
                            'post_parent' => 18,
                            '_kwps_sort_order' => 0,
                            'post_status' => 'draft',
                            'post_content' => 'Question 1',
                            'answer_options' => array(
                                0 => array(
                                    'ID' => 21,
                                    'post_parent' => 19,
                                    '_kwps_sort_order' => 0,
                                    'post_content' => 'Answer option 2',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 10,
                                ),
                                1 => array(
                                    'ID' => 22,
                                    'post_parent' => 19,
                                    '_kwps_sort_order' => 1,
                                    'post_content' => 'Answer option 3',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 15,
                                ),
                            ),
                        ),
                        1 => array(
                            'ID' => 23,
                            'post_parent' => 18,
                            '_kwps_sort_order' => 1,
                            'post_status' => 'draft',
                            'post_content' => 'Question 2',
                            'answer_options' => array(
                                0 => array(
                                    'ID' => 24,
                                    'post_parent' => 23,
                                    '_kwps_sort_order' => 0,
                                    'post_content' => 'Answer option 1',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 5,
                                ),
                                1 => array(
                                    'ID' => 25,
                                    'post_parent' => 23,
                                    '_kwps_sort_order' => 1,
                                    'post_content' => 'Answer option 2',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 10,
                                ),
                                2 => array(
                                    'ID' => 26,
                                    'post_parent' => 23,
                                    '_kwps_sort_order' => 2,
                                    'post_content' => 'Answer option 3',
                                    'post_status' => 'draft',
                                    '_kwps_answer_option_value' => 15,
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);