<?php
return array(
    'ID' => 5,
    'post_title' => 'New Version',
    'post_parent' => 4,
    'post_status' => 'draft',
    '_kwps_sort_order' => 0,
    '_kwps_view_count' => 0,
    'intro' => array(
        'ID' => 6,
        'post_content' => 'Intro contents',
        '_kwps_sort_order' => 0,
        'post_status' => 'draft',
        'post_parent' => 5,
    ),
    'intro_result' => array(
        'ID' => 7,
        'post_content' => 'Intro result contents',
        '_kwps_sort_order' => 0,
        'post_status' => 'draft',
        'post_parent' => 5,
    ),
    'outro' => array(
        'ID' => 8,
        'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
        '_kwps_sort_order' => 0,
        'post_status' => 'draft',
        'post_parent' => 5,
    ),
    'question_groups' => array(
        0 => array(
            'ID' => 9,
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_title' => 'Question page 1',
            'post_content' => 'These are the questions of page 1',
            'post_parent' => 5,
            'questions' => array(
                1 => array(
                    'ID' => 10,
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_content' => 'Question 1',
                    'post_parent' => 9,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 11,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 10,
                        ),
                        1 => array(
                            'ID' => 12,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 10,
                        ),
                        2 => array(
                            'ID' => 13,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 10,
                        ),
                    ),
                ),
                2 => array(
                    'ID' => 14,
                    '_kwps_sort_order' => 1,
                    'post_status' => 'draft',
                    'post_content' => 'Question 2',
                    'post_parent' => 9,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 15,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 14,
                        ),
                        1 => array(
                            'ID' => 16,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 14,
                        ),
                        2 => array(
                            'ID' => 17,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 14,
                        ),
                    ),
                ),
                3 => array(
                    'ID' => 18,
                    '_kwps_sort_order' => 2,
                    'post_status' => 'draft',
                    'post_content' => 'Question 3',
                    'post_parent' => 9,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 19,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 18,
                        ),
                        1 => array(
                            'ID' => 20,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 18,
                        ),
                        2 => array(
                            'ID' => 21,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 18,
                        ),
                    ),
                ),
            ),
        ),
        1 => array(
            'ID' => 22,
            '_kwps_sort_order' => 1,
            'post_status' => 'draft',
            'post_title' => 'Question page 2',
            'post_content' => 'These are the questions of page 2',
            'post_parent' => 5,
            'questions' => array(
                1 => array(
                    'ID' => 23,
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_content' => 'Question 1',
                    'post_parent' => 22,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 24,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 23,
                        ),
                        1 => array(
                            'ID' => 25,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 23,
                        ),
                        2 => array(
                            'ID' => 26,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 23,
                        ),
                    ),
                ),
                2 => array(
                    'ID' => 27,
                    '_kwps_sort_order' => 1,
                    'post_status' => 'draft',
                    'post_content' => 'Question 2',
                    'post_parent' => 22,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 28,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 27,
                        ),
                        1 => array(
                            'ID' => 29,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 27,
                        ),
                        2 => array(
                            'ID' => 30,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 27,
                        ),
                    ),
                ),
                3 => array(
                    'ID' => 31,
                    '_kwps_sort_order' => 2,
                    'post_status' => 'draft',
                    'post_content' => 'Question 3',
                    'post_parent' => 22,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 32,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 31,
                        ),
                        1 => array(
                            'ID' => 33,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 31,
                        ),
                        2 => array(
                            'ID' => 34,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 31,
                        ),
                    ),
                ),
            ),
        ),
        2 => array(
            'ID' => 35,
            '_kwps_sort_order' => 2,
            'post_status' => 'draft',
            'post_title' => 'Question page 3',
            'post_content' => 'These are the questions of page 3',
            'post_parent' => 5,
            'questions' => array(
                1 => array(
                    'ID' => 36,
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_content' => 'Question 1',
                    'post_parent' => 35,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 37,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 36,
                        ),
                        1 => array(
                            'ID' => 38,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 36,
                        ),
                        2 => array(
                            'ID' => 39,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 36,
                        ),
                    ),
                ),
                2 => array(
                    'ID' => 40,
                    '_kwps_sort_order' => 1,
                    'post_status' => 'draft',
                    'post_content' => 'Question 2',
                    'post_parent' => 35,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 41,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 40,
                        ),
                        1 => array(
                            'ID' => 42,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 40,
                        ),
                        2 => array(
                            'ID' => 43,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 40,
                        ),
                    ),
                ),
                3 => array(
                    'ID' => 44,
                    '_kwps_sort_order' => 2,
                    'post_status' => 'draft',
                    'post_content' => 'Question 3',
                    'post_parent' => 35,
                    'answer_options' => array(
                        0 => array(
                            'ID' => 45,
                            '_kwps_sort_order' => 0,
                            'post_content' => 'Answer option 1',
                            'post_status' => 'draft',
                            'post_parent' => 44,
                        ),
                        1 => array(
                            'ID' => 46,
                            '_kwps_sort_order' => 1,
                            'post_content' => 'Answer option 2',
                            'post_status' => 'draft',
                            'post_parent' => 44,
                        ),
                        2 => array(
                            'ID' => 47,
                            '_kwps_sort_order' => 2,
                            'post_content' => 'Answer option 3',
                            'post_status' => 'draft',
                            'post_parent' => 44,
                        ),
                    ),
                ),
            ),
        ),
    ),
);