<?php
return array(
    'input' => array(
        'ID' => 5,
        'post_title' => 'New Version',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 0,
        '_kwps_view_count' => 0,
        'intro' => array(
            'ID' => 6,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'intro_result' => array(
            'ID' => 7,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'outro' => array(
            'ID' => 8,
            'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'question_groups' => array(
            0 => array(
                'ID' => 9,
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'post_parent' => 5,
                'questions' => array(
                    1 => array(
                        'ID' => 10,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'post_parent' => 9,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 11,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                            1 => array(
                                'ID' => 12,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                            2 => array(
                                'ID' => 13,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                            3 => array(
                                '_kwps_sort_order' => 3,
                                'post_content' => 'Answer option 4',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                        ),
                    ),
                ),
            ),

        ),
    ),
    'expected_output' => array(
        array(
            'errors' => false,
            'test_modus_errors' => array(),
            'data' => array(
                'ID' => 5,
                'post_title' => 'New Version',
                'post_parent' => 4,
                'post_status' => 'draft',
                '_kwps_sort_order' => 0,
                '_kwps_view_count' => 0,
                'intro' => array(
                    'ID' => 6,
                    'post_content' => 'Intro contents',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 5,
                ),
                'intro_result' => array(
                    'ID' => 7,
                    'post_content' => 'Intro result contents',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 5,
                ),
                'outro' => array(
                    'ID' => 8,
                    'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 5,
                ),
                'question_groups' => array(
                    0 => array(
                        'ID' => 9,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_title' => 'Question page 1',
                        'post_content' => 'These are the questions of page 1',
                        'post_parent' => 5,
                        'questions' => array(
                            0 => array(
                                'ID' => 10,
                                '_kwps_sort_order' => 0,
                                'post_status' => 'draft',
                                'post_content' => 'Question 1',
                                'post_parent' => 9,
                                'answer_options' => array(
                                    0 => array(
                                        'ID' => 11,
                                        '_kwps_sort_order' => 0,
                                        'post_content' => 'Answer option 1',
                                        'post_status' => 'draft',
                                        'post_parent' => 10,
                                    ),
                                    1 => array(
                                        'ID' => 12,
                                        '_kwps_sort_order' => 1,
                                        'post_content' => 'Answer option 2',
                                        'post_status' => 'draft',
                                        'post_parent' => 10,
                                    ),
                                    2 => array(
                                        'ID' => 13,
                                        '_kwps_sort_order' => 2,
                                        'post_content' => 'Answer option 3',
                                        'post_status' => 'draft',
                                        'post_parent' => 10,
                                    ),
                                    3 => array(
                                        'ID' => 32,
                                        '_kwps_sort_order' => 3,
                                        'post_content' => 'Answer option 4',
                                        'post_status' => 'draft',
                                        'post_parent' => 10,
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'errors' => false,
            'test_modus_errors' => array(),
            'data' => array(
                'ID' => 14,
                'post_title' => 'New Version - 2',
                'post_parent' => 4,
                'post_status' => 'draft',
                '_kwps_sort_order' => 1,
                '_kwps_view_count' => 0,
                'intro' => array(
                    'ID' => 15,
                    'post_content' => 'Intro contents',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 14,
                ),
                'intro_result' => array(
                    'ID' => 16,
                    'post_content' => 'Intro result contents',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 14,
                ),
                'outro' => array(
                    'ID' => 17,
                    'post_content' => 'Outro contents [kwps_result result=pie-chart-per-question]',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 14,
                ),
                'question_groups' => array(
                    0 => array(
                        'ID' => 18,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_title' => 'Question page 1',
                        'post_content' => 'These are the questions of page 1',
                        'post_parent' => 14,
                        'questions' => array(
                            0 => array(
                                'ID' => 19,
                                '_kwps_sort_order' => 0,
                                'post_status' => 'draft',
                                'post_content' => 'Question 1',
                                'post_parent' => 18,
                                'answer_options' => array(
                                    0 => array(
                                        'ID' => 20,
                                        '_kwps_sort_order' => 0,
                                        'post_content' => 'Answer option 1',
                                        'post_status' => 'draft',
                                        'post_parent' => 19,
                                    ),
                                    1 => array(
                                        'ID' => 21,
                                        '_kwps_sort_order' => 1,
                                        'post_content' => 'Answer option 2',
                                        'post_status' => 'draft',
                                        'post_parent' => 19,
                                    ),
                                    2 => array(
                                        'ID' => 22,
                                        '_kwps_sort_order' => 2,
                                        'post_content' => 'Answer option 3',
                                        'post_status' => 'draft',
                                        'post_parent' => 19,
                                    ),
                                    3 => array(
                                        'ID' => 33,
                                        '_kwps_sort_order' => 3,
                                        'post_content' => 'Answer option 4',
                                        'post_status' => 'draft',
                                        'post_parent' => 19,
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'errors' => false,
            'test_modus_errors' => array(),
            'data' => array(
                'ID' => 23,
                'post_title' => 'New Version - 3',
                'post_parent' => 4,
                'post_status' => 'draft',
                '_kwps_sort_order' => 2,
                '_kwps_view_count' => 0,
                'intro' => array(
                    'ID' => 24,
                    'post_content' => 'Intro contents',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 23,
                ),
                'intro_result' => array(
                    'ID' => 25,
                    'post_content' => 'Intro result contents',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 23,
                ),
                'outro' => array(
                    'ID' => 26,
                    'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
                    '_kwps_sort_order' => 0,
                    'post_status' => 'draft',
                    'post_parent' => 23,
                ),
                'question_groups' => array(
                    0 => array(
                        'ID' => 27,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_title' => 'Question page 1',
                        'post_content' => 'These are the questions of page 1',
                        'post_parent' => 23,
                        'questions' => array(
                            0 => array(
                                'ID' => 28,
                                '_kwps_sort_order' => 0,
                                'post_status' => 'draft',
                                'post_content' => 'Question 1',
                                'post_parent' => 27,
                                'answer_options' => array(
                                    0 => array(
                                        'ID' => 29,
                                        '_kwps_sort_order' => 0,
                                        'post_content' => 'Answer option 1',
                                        'post_status' => 'draft',
                                        'post_parent' => 28,
                                    ),
                                    1 => array(
                                        'ID' => 30,
                                        '_kwps_sort_order' => 1,
                                        'post_content' => 'Answer option 2',
                                        'post_status' => 'draft',
                                        'post_parent' => 28,
                                    ),
                                    2 => array(
                                        'ID' => 31,
                                        '_kwps_sort_order' => 2,
                                        'post_content' => 'Answer option 3',
                                        'post_status' => 'draft',
                                        'post_parent' => 28,
                                    ),
                                    3 => array(
                                        'ID' => 34,
                                        '_kwps_sort_order' => 3,
                                        'post_content' => 'Answer option 4',
                                        'post_status' => 'draft',
                                        'post_parent' => 28,
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);