<?php
return array(
    'input' => array(
        'ID' => 5,
        'post_title' => 'New Version',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 0,
        '_kwps_view_count' => 0,
        'intro' => array(
            'ID' => 6,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'intro_result' => array(
            'ID' => 7,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'outro' => array(
            'ID' => 8,
            'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
            'post_parent' => 5,
        ),
        'question_groups' => array(
            0 => array(
                'ID' => 9,
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'post_parent' => 5,
                'questions' => array(
                    1 => array(
                        'ID' => 10,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'post_parent' => 9,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 11,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                            1 => array(
                                'ID' => 12,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                            2 => array(
                                'ID' => 13,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 10,
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 14,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'post_parent' => 9,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 15,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 14,
                            ),
                            1 => array(
                                'ID' => 16,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 14,
                            ),
                            2 => array(
                                'ID' => 17,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 14,
                            ),
                        ),
                    ),
                    3 => array(
                        'ID' => 18,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'post_parent' => 9,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 19,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 18,
                            ),
                            1 => array(
                                'ID' => 20,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 18,
                            ),
                            2 => array(
                                'ID' => 21,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 18,
                            ),
                        ),
                    ),
                ),
            ),
            1 => array(
                'ID' => 22,
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
                'post_title' => 'Question page 2',
                'post_content' => 'These are the questions of page 2',
                'post_parent' => 5,
                'questions' => array(
                    1 => array(
                        'ID' => 23,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'trash',
                        'post_content' => 'Question 1',
                        'post_parent' => 22,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 24,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 23,
                            ),
                            1 => array(
                                'ID' => 25,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 23,
                            ),
                            2 => array(
                                'ID' => 26,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 23,
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 27,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'post_parent' => 22,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 28,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 27,
                            ),
                            1 => array(
                                'ID' => 29,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 27,
                            ),
                            2 => array(
                                'ID' => 30,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 27,
                            ),
                        ),
                    ),
                    3 => array(
                        'ID' => 31,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'post_parent' => 22,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 32,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 31,
                            ),
                            1 => array(
                                'ID' => 33,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 31,
                            ),
                            2 => array(
                                'ID' => 34,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 31,
                            ),
                        ),
                    ),
                ),
            ),
            2 => array(
                'ID' => 35,
                '_kwps_sort_order' => 2,
                'post_status' => 'draft',
                'post_title' => 'Question page 3',
                'post_content' => 'These are the questions of page 3',
                'post_parent' => 5,
                'questions' => array(
                    1 => array(
                        'ID' => 36,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'post_parent' => 35,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 37,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 36,
                            ),
                            1 => array(
                                'ID' => 38,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 36,
                            ),
                            2 => array(
                                'ID' => 39,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 36,
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 40,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'post_parent' => 35,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 41,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 40,
                            ),
                            1 => array(
                                'ID' => 42,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 40,
                            ),
                            2 => array(
                                'ID' => 43,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 40,
                            ),
                        ),
                    ),
                    3 => array(
                        'ID' => 44,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'post_parent' => 35,
                        'answer_options' => array(
                            0 => array(
                                'ID' => 45,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                                'post_parent' => 44,
                            ),
                            1 => array(
                                'ID' => 46,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                                'post_parent' => 44,
                            ),
                            2 => array(
                                'ID' => 47,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                                'post_parent' => 44,
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'expected_output' => array(
    array(
        'ID' => 5,
        'post_title' => 'New Version',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 0,
        '_kwps_view_count' => 0,
        'intro' => array(
            'ID' => 6,
            'post_parent' => 5,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'intro_result' => array(
            'ID' => 7,
            'post_parent' => 5,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'outro' => array(
            'ID' => 8,
            'post_parent' => 5,
            'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'question_groups' => array(
            0 => array(
                'ID' => 9,
                'post_parent' => 5,
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'questions' => array(
                    0 => array(
                        'ID' => 10,
                        'post_parent' => 9,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 11,
                                'post_parent' => 10,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 12,
                                'post_parent' => 10,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 13,
                                'post_parent' => 10,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 14,
                        'post_parent' => 9,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 15,
                                'post_parent' => 14,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 16,
                                'post_parent' => 14,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 17,
                                'post_parent' => 14,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 18,
                        'post_parent' => 9,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 19,
                                'post_parent' => 18,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 20,
                                'post_parent' => 18,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 21,
                                'post_parent' => 18,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
            1 => array(
                'ID' => 22,
                'post_parent' => 5,
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
                'post_title' => 'Question page 2',
                'post_content' => 'These are the questions of page 2',
                'questions' => array(
//                    0 => array(
//                        'ID' => 23,
//                        'post_parent' => 22,
//                        '_kwps_sort_order' => 0,
//                        'post_status' => 'draft',
//                        'post_content' => 'Question 1',
//                        'answer_options' => array(
//                            0 => array(
//                                'ID' => 24,
//                                'post_parent' => 23,
//                                '_kwps_sort_order' => 0,
//                                'post_content' => 'Answer option 1',
//                                'post_status' => 'draft',
//                            ),
//                            1 => array(
//                                'ID' => 25,
//                                'post_parent' => 23,
//                                '_kwps_sort_order' => 1,
//                                'post_content' => 'Answer option 2',
//                                'post_status' => 'draft',
//                            ),
//                            2 => array(
//                                'ID' => 26,
//                                'post_parent' => 23,
//                                '_kwps_sort_order' => 2,
//                                'post_content' => 'Answer option 3',
//                                'post_status' => 'draft',
//                            ),
//                        ),
//                    ),
                    0 => array(
                        'ID' => 27,
                        'post_parent' => 22,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 28,
                                'post_parent' => 27,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 29,
                                'post_parent' => 27,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 30,
                                'post_parent' => 27,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 31,
                        'post_parent' => 22,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 32,
                                'post_parent' => 31,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 33,
                                'post_parent' => 31,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 34,
                                'post_parent' => 31,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
            2 => array(
                'ID' => 35,
                'post_parent' => 5,
                '_kwps_sort_order' => 2,
                'post_status' => 'draft',
                'post_title' => 'Question page 3',
                'post_content' => 'These are the questions of page 3',
                'questions' => array(
                    0 => array(
                        'ID' => 36,
                        'post_parent' => 35,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 37,
                                'post_parent' => 36,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 38,
                                'post_parent' => 36,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 39,
                                'post_parent' => 36,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 40,
                        'post_parent' => 35,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 41,
                                'post_parent' => 40,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 42,
                                'post_parent' => 40,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 43,
                                'post_parent' => 40,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 44,
                        'post_parent' => 35,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 45,
                                'post_parent' => 44,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 46,
                                'post_parent' => 44,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 47,
                                'post_parent' => 44,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),

        ),
    ),
    array(
        'ID' => 48,
        'post_title' => 'New Version - 2',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 1,
        '_kwps_view_count' => 0,
        'intro' => array(
            'ID' => 49,
            'post_parent' => 48,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'intro_result' => array(
            'ID' => 50,
            'post_parent' => 48,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'outro' => array(
            'ID' => 51,
            'post_parent' => 48,
            'post_content' => 'Outro contents [kwps_result result=pie-chart-per-question]',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'question_groups' => array(
            0 => array(
                'ID' => 52,
                'post_parent' => 48,
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'questions' => array(
                    0 => array(
                        'ID' => 53,
                        'post_parent' => 52,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 54,
                                'post_parent' => 53,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 55,
                                'post_parent' => 53,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 56,
                                'post_parent' => 53,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 57,
                        'post_parent' => 52,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 58,
                                'post_parent' => 57,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 59,
                                'post_parent' => 57,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 60,
                                'post_parent' => 57,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 61,
                        'post_parent' => 52,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 62,
                                'post_parent' => 61,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 63,
                                'post_parent' => 61,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 64,
                                'post_parent' => 61,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
            1 => array(
                'ID' => 65,
                'post_parent' => 48,
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
                'post_title' => 'Question page 2',
                'post_content' => 'These are the questions of page 2',
                'questions' => array(
//                    0 => array(
//                        'ID' => 66,
//                        'post_parent' => 65,
//                        '_kwps_sort_order' => 0,
//                        'post_status' => 'draft',
//                        'post_content' => 'Question 1',
//                        'answer_options' => array(
//                            0 => array(
//                                'ID' => 67,
//                                'post_parent' => 66,
//                                '_kwps_sort_order' => 0,
//                                'post_content' => 'Answer option 1',
//                                'post_status' => 'draft',
//                            ),
//                            1 => array(
//                                'ID' => 68,
//                                'post_parent' => 66,
//                                '_kwps_sort_order' => 1,
//                                'post_content' => 'Answer option 2',
//                                'post_status' => 'draft',
//                            ),
//                            2 => array(
//                                'ID' => 69,
//                                'post_parent' => 66,
//                                '_kwps_sort_order' => 2,
//                                'post_content' => 'Answer option 3',
//                                'post_status' => 'draft',
//                            ),
//                        ),
//                    ),
                    0 => array(
                        'ID' => 70,
                        'post_parent' => 65,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 71,
                                'post_parent' => 70,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 72,
                                'post_parent' => 70,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 73,
                                'post_parent' => 70,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 74,
                        'post_parent' => 65,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 75,
                                'post_parent' => 74,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 76,
                                'post_parent' => 74,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 77,
                                'post_parent' => 74,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
            2 => array(
                'ID' => 78,
                'post_parent' => 48,
                '_kwps_sort_order' => 2,
                'post_status' => 'draft',
                'post_title' => 'Question page 3',
                'post_content' => 'These are the questions of page 3',
                'questions' => array(
                    0 => array(
                        'ID' => 79,
                        'post_parent' => 78,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 80,
                                'post_parent' => 79,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 81,
                                'post_parent' => 79,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 82,
                                'post_parent' => 79,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 83,
                        'post_parent' => 78,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 84,
                                'post_parent' => 83,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 85,
                                'post_parent' => 83,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 86,
                                'post_parent' => 83,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 87,
                        'post_parent' => 78,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 88,
                                'post_parent' => 87,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 89,
                                'post_parent' => 87,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 90,
                                'post_parent' => 87,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),

        ),
    ),
    array(
        'ID' => 91,
        'post_title' => 'New Version - 3',
        'post_parent' => 4,
        'post_status' => 'draft',
        '_kwps_sort_order' => 2,
        '_kwps_view_count' => 0,
        'intro' => array(
            'ID' => 92,
            'post_parent' => 91,
            'post_content' => 'Intro contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'intro_result' => array(
            'ID' => 93,
            'post_parent' => 91,
            'post_content' => 'Intro result contents',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'outro' => array(
            'ID' => 94,
            'post_parent' => 91,
            'post_content' => 'Outro contents [kwps_result result=bar-chart-per-question]',
            '_kwps_sort_order' => 0,
            'post_status' => 'draft',
        ),
        'question_groups' => array(
            0 => array(
                'ID' => 95,
                'post_parent' => 91,
                '_kwps_sort_order' => 0,
                'post_status' => 'draft',
                'post_title' => 'Question page 1',
                'post_content' => 'These are the questions of page 1',
                'questions' => array(
                    0 => array(
                        'ID' => 96,
                        'post_parent' => 95,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 97,
                                'post_parent' => 96,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 98,
                                'post_parent' => 96,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 99,
                                'post_parent' => 96,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 100,
                        'post_parent' => 95,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 101,
                                'post_parent' => 100,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 102,
                                'post_parent' => 100,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 103,
                                'post_parent' => 100,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 104,
                        'post_parent' => 95,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 105,
                                'post_parent' => 104,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 106,
                                'post_parent' => 104,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 107,
                                'post_parent' => 104,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
            1 => array(
                'ID' => 108,
                'post_parent' => 91,
                '_kwps_sort_order' => 1,
                'post_status' => 'draft',
                'post_title' => 'Question page 2',
                'post_content' => 'These are the questions of page 2',
                'questions' => array(
//                    0 => array(
//                        'ID' => 109,
//                        'post_parent' => 108,
//                        '_kwps_sort_order' => 0,
//                        'post_status' => 'draft',
//                        'post_content' => 'Question 1',
//                        'answer_options' => array(
//                            0 => array(
//                                'ID' => 110,
//                                'post_parent' => 109,
//                                '_kwps_sort_order' => 0,
//                                'post_content' => 'Answer option 1',
//                                'post_status' => 'draft',
//                            ),
//                            1 => array(
//                                'ID' => 111,
//                                'post_parent' => 109,
//                                '_kwps_sort_order' => 1,
//                                'post_content' => 'Answer option 2',
//                                'post_status' => 'draft',
//                            ),
//                            2 => array(
//                                'ID' => 112,
//                                'post_parent' => 109,
//                                '_kwps_sort_order' => 2,
//                                'post_content' => 'Answer option 3',
//                                'post_status' => 'draft',
//                            ),
//                        ),
//                    ),
                    0 => array(
                        'ID' => 113,
                        'post_parent' => 108,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 114,
                                'post_parent' => 113,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 115,
                                'post_parent' => 113,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 116,
                                'post_parent' => 113,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 117,
                        'post_parent' => 108,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 118,
                                'post_parent' => 117,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 119,
                                'post_parent' => 117,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 120,
                                'post_parent' => 117,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
            2 => array(
                'ID' => 121,
                'post_parent' => 91,
                '_kwps_sort_order' => 2,
                'post_status' => 'draft',
                'post_title' => 'Question page 3',
                'post_content' => 'These are the questions of page 3',
                'questions' => array(
                    0 => array(
                        'ID' => 122,
                        'post_parent' => 121,
                        '_kwps_sort_order' => 0,
                        'post_status' => 'draft',
                        'post_content' => 'Question 1',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 123,
                                'post_parent' => 122,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 124,
                                'post_parent' => 122,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 125,
                                'post_parent' => 122,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    1 => array(
                        'ID' => 126,
                        'post_parent' => 121,
                        '_kwps_sort_order' => 1,
                        'post_status' => 'draft',
                        'post_content' => 'Question 2',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 127,
                                'post_parent' => 126,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 128,
                                'post_parent' => 126,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 129,
                                'post_parent' => 126,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                    2 => array(
                        'ID' => 130,
                        'post_parent' => 121,
                        '_kwps_sort_order' => 2,
                        'post_status' => 'draft',
                        'post_content' => 'Question 3',
                        'answer_options' => array(
                            0 => array(
                                'ID' => 131,
                                'post_parent' => 130,
                                '_kwps_sort_order' => 0,
                                'post_content' => 'Answer option 1',
                                'post_status' => 'draft',
                            ),
                            1 => array(
                                'ID' => 132,
                                'post_parent' => 130,
                                '_kwps_sort_order' => 1,
                                'post_content' => 'Answer option 2',
                                'post_status' => 'draft',
                            ),
                            2 => array(
                                'ID' => 133,
                                'post_parent' => 130,
                                '_kwps_sort_order' => 2,
                                'post_content' => 'Answer option 3',
                                'post_status' => 'draft',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
);